/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(registrarse)'}/registroDiscapacidad` | `/registroDiscapacidad`; params?: Router.UnknownInputParams; } | { pathname: `/contexts/authContext`; params?: Router.UnknownInputParams; } | { pathname: `/iniciar-sesion/ayudaPass`; params?: Router.UnknownInputParams; } | { pathname: `/iniciar-sesion/homeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/iniciar-sesion/inputError`; params?: Router.UnknownInputParams; } | { pathname: `/iniciar-sesion/loginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/iniciar-sesion/nuevaPass`; params?: Router.UnknownInputParams; } | { pathname: `/iniciar-sesion/splashScreen`; params?: Router.UnknownInputParams; } | { pathname: `/iniciar-sesion/verificacionEmail`; params?: Router.UnknownInputParams; } | { pathname: `/iniciar-sesion/verificacionTelefono`; params?: Router.UnknownInputParams; } | { pathname: `/services/authService`; params?: Router.UnknownInputParams; } | { pathname: `/services/tokenService`; params?: Router.UnknownInputParams; } | { pathname: `/utils/axios`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(registrarse)'}/registroDiscapacidad` | `/registroDiscapacidad`; params?: Router.UnknownOutputParams; } | { pathname: `/contexts/authContext`; params?: Router.UnknownOutputParams; } | { pathname: `/iniciar-sesion/ayudaPass`; params?: Router.UnknownOutputParams; } | { pathname: `/iniciar-sesion/homeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/iniciar-sesion/inputError`; params?: Router.UnknownOutputParams; } | { pathname: `/iniciar-sesion/loginScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/iniciar-sesion/nuevaPass`; params?: Router.UnknownOutputParams; } | { pathname: `/iniciar-sesion/splashScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/iniciar-sesion/verificacionEmail`; params?: Router.UnknownOutputParams; } | { pathname: `/iniciar-sesion/verificacionTelefono`; params?: Router.UnknownOutputParams; } | { pathname: `/services/authService`; params?: Router.UnknownOutputParams; } | { pathname: `/services/tokenService`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/axios`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(registrarse)'}/registroDiscapacidad${`?${string}` | `#${string}` | ''}` | `/registroDiscapacidad${`?${string}` | `#${string}` | ''}` | `/contexts/authContext${`?${string}` | `#${string}` | ''}` | `/iniciar-sesion/ayudaPass${`?${string}` | `#${string}` | ''}` | `/iniciar-sesion/homeScreen${`?${string}` | `#${string}` | ''}` | `/iniciar-sesion/inputError${`?${string}` | `#${string}` | ''}` | `/iniciar-sesion/loginScreen${`?${string}` | `#${string}` | ''}` | `/iniciar-sesion/nuevaPass${`?${string}` | `#${string}` | ''}` | `/iniciar-sesion/splashScreen${`?${string}` | `#${string}` | ''}` | `/iniciar-sesion/verificacionEmail${`?${string}` | `#${string}` | ''}` | `/iniciar-sesion/verificacionTelefono${`?${string}` | `#${string}` | ''}` | `/services/authService${`?${string}` | `#${string}` | ''}` | `/services/tokenService${`?${string}` | `#${string}` | ''}` | `/utils/axios${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(registrarse)'}/registroDiscapacidad` | `/registroDiscapacidad`; params?: Router.UnknownInputParams; } | { pathname: `/contexts/authContext`; params?: Router.UnknownInputParams; } | { pathname: `/iniciar-sesion/ayudaPass`; params?: Router.UnknownInputParams; } | { pathname: `/iniciar-sesion/homeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/iniciar-sesion/inputError`; params?: Router.UnknownInputParams; } | { pathname: `/iniciar-sesion/loginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/iniciar-sesion/nuevaPass`; params?: Router.UnknownInputParams; } | { pathname: `/iniciar-sesion/splashScreen`; params?: Router.UnknownInputParams; } | { pathname: `/iniciar-sesion/verificacionEmail`; params?: Router.UnknownInputParams; } | { pathname: `/iniciar-sesion/verificacionTelefono`; params?: Router.UnknownInputParams; } | { pathname: `/services/authService`; params?: Router.UnknownInputParams; } | { pathname: `/services/tokenService`; params?: Router.UnknownInputParams; } | { pathname: `/utils/axios`; params?: Router.UnknownInputParams; };
    }
  }
}
